version: "3"
services:
  express-bosta:
    build: .
    # platform: linux/x86_64
    # image: express-bosta
    container_name: expres-bosta-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    networks:
      - express-mysql-network
    depends_on:
      - mysql
      # - postgres
      - redis
    volumes:       
      - ./public:/usr/src/app/public
  mysql:
    image: mysql
    restart: always
    platform: linux/amd64
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - express-mysql-network
    ports:
      - 3306:3306   
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db_express
      # MYSQL_USER: root
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - express-mysql-network


volumes:
  mysql-db:

networks: 
  express-mysql-network: