version: "3"
services:
  express-bosta:
    build: 
      context: .
      target: local
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./.env.local
    environment:
      - NODE_ENV=development
    command: npm run dev