version: "3"
services:
  express-bosta:
    build: .
    # platform: linux/x86_64
    # image: express-bosta
    container_name: expres-bosta-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mysql
      # - postgres
      - redis
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bosta
      MYSQL_USER: root
      MYSQL_PASSWORD: example
  redis:
    image: redis


volumes:
  mysql-db: